### ISSUE TITLE
Some posts in feed being grabbed as 'handle.invalid', causing some posts to be grabbed twice

### ISSUE THREAD

**Issue by infinitephantasm** [MissMeridian/bluesky-discord-monitor#1] opened 2024-11-14 22:40 UTC
for some reason, posts in a feed will occasionally be pulled and posted under `handle.invalid`, rather than the intended handle, causing some posts to be sent twice by accident for unknown reasons (and then added into `archived.json`).

not entirely sure as to why this is happening; if it matters, i modified the code for myself specifically to also grab reposts since my intent was for it to grab from an account that almost always reposts content.

**Comment by MissMeridian** [comment] 2024-11-15 17:21
Hi! Last night, Bluesky was having some network issues which resulted in a lot of bsky.social handles being temporarily unavailable. I'm quite confident this was caused by that outage, since I experienced the duplicated messages on my locally running copy.

Just in case this occurs again, I'm going to implement a condition that rejects invalid handles, since this could also occur if the atproto DNS record is lost on a domain, and the handle becomes invalid.

**Comment by MissMeridian** [comment] 2024-11-15 18:26
**Fixed in commit https://github.com/MissMeridian/bluesky-discord-monitor/commit/526ca4c94dddab327d4b427bb3e6778605cf2782.** Any invalid handles will be ignored and not processed, providing a warning message with potential causes.

As for reposts, I was planning on creating interpretation for them later down the line. If you feel brave enough and have a good way of separating reposts from posts, create a fork of the repository and submit a pull request! 

(This has been my first ever issue and has been a learning experience for me, so I appreciate you for reporting this!)

**Closed as completed by MissMeridian** 2024-11-15 18:26 UTC
Labels: bug
